const Arrow = () => <span aria-hidden="true" className="arrow">↗</span>;
const PrismMark = () => <span className="prism-mark" aria-hidden="true"><i /><i /><i /></span>;

function EstimatePreview({ compact = false }: { compact?: boolean }) {
  return <div className={`app-window estimate-window ${compact ? "compact" : ""}`}>
    <div className="window-top"><div className="app-brand"><PrismMark /> ПРИЗМА <span>/ Экспертная смета</span></div><div className="save-state">● Сохранено</div></div>
    <div className="workspace">
      <aside className="side-nav"><b>Исследование</b><span className="active">Смета</span><span>Исходные данные</span><span>Источники</span><span>Отчёт</span></aside>
      <div className="estimate-main">
        <div className="crumb">Экспертная смета <span>·</span> ES-2406-014</div>
        <div className="estimate-title"><div><h3>Кухонный гарнитур</h3><p>Устранение выявленных недостатков</p></div><button className="export">Экспорт отчёта</button></div>
        <div className="table-wrap"><table><thead><tr><th>Позиция</th><th>Кол-во</th><th>Цена</th><th>Стоимость</th></tr></thead><tbody><tr><td><span className="dot material" /> Фасад МДФ, эмаль</td><td>6 шт.</td><td>18 400 ₽</td><td>110 400 ₽</td></tr><tr><td><span className="dot material" /> Столешница HPL</td><td>1 шт.</td><td>56 800 ₽</td><td>56 800 ₽</td></tr><tr><td><span className="dot work" /> Монтажные работы</td><td>24 ч.</td><td>3 950 ₽</td><td>94 800 ₽</td></tr></tbody></table></div>
      </div>
      <aside className="estimate-total"><span>СТОИМОСТЬ РАБОТ</span><strong>361 800 ₽</strong><div><p>Материалы <b>248 600 ₽</b></p><p>Работы <b>94 800 ₽</b></p><p>Прочие расходы <b>18 400 ₽</b></p></div><button>Посмотреть расчёт <Arrow /></button></aside>
    </div>
  </div>;
}

function IndexChart() {
  return <div className="index-ui">
    <div className="index-toolbar"><div><span className="eyeline">ИНДЕКС / КАТЕГОРИЯ</span><b>Мебель для дома</b></div><div><span className="eyeline">ПЕРИОД РАСЧЁТА</span><b>Январь 2024 <i>→</i> Июль 2026</b></div><button>Источник: Росстат ↘</button></div>
    <div className="index-content"><div className="index-metric"><span>ИСХОДНАЯ СТОИМОСТЬ</span><b className="original-value">100 000 ₽</b><div className="metric-pair"><div><span>КОЭФФИЦИЕНТ</span><strong>1,174</strong></div><div><span>ИЗМЕНЕНИЕ</span><em>+17,4 %</em></div></div><hr /><small>РАССЧИТАННАЯ СТОИМОСТЬ<br /><b>117 400 ₽</b></small></div><div className="chart"><div className="chart-labels"><span>1,20</span><span>1,15</span><span>1,10</span><span>1,05</span></div><svg viewBox="0 0 600 200" preserveAspectRatio="none" aria-label="График изменения индекса цен"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#097c77" stopOpacity=".22"/><stop offset="1" stopColor="#097c77" stopOpacity="0"/></linearGradient></defs><path d="M0 183 L35 171 L67 175 L100 152 L133 161 L167 139 L200 145 L234 119 L267 125 L300 108 L334 112 L367 87 L400 92 L434 66 L467 70 L500 42 L533 51 L567 27 L600 14 V200 H0Z" fill="url(#area)"/><path d="M0 183 L35 171 L67 175 L100 152 L133 161 L167 139 L200 145 L234 119 L267 125 L300 108 L334 112 L367 87 L400 92 L434 66 L467 70 L500 42 L533 51 L567 27 L600 14" fill="none" stroke="#097c77" strokeWidth="3"/><circle cx="567" cy="27" r="5" fill="#fff" stroke="#097c77" strokeWidth="3"/></svg><div className="axis"><span>Янв. 24</span><span>Янв. 25</span><span>Янв. 26</span><span>Июл. 26</span></div></div></div>
  </div>;
}

export default function App() {
  return <main>
    <header className="site-header"><a className="logo" href="#top"><PrismMark /> <span>ПРИЗМА</span></a><nav><a href="#capabilities">Возможности</a><a href="#estimate">Смета</a><a href="#indices">Индексы</a><a href="#pricing">Тарифы</a><a href="#knowledge">База знаний</a></nav><div className="header-actions"><a href="#login" className="login">Войти</a><a href="#start" className="button primary">Начать работу <Arrow /></a></div></header>

    <section className="hero" id="top"><div className="hero-copy"><p className="overline">PRISMCORE <span>·</span> PROFESSIONAL EXPERT SOFTWARE</p><h1>Профессиональная<br />платформа <i>для</i> <span>работы</span><br />эксперта</h1><p className="intro">Инструменты для расчётов, анализа данных и подготовки экспертных исследований — в единой рабочей среде.</p><div className="hero-actions"><a href="#start" className="button primary">Начать работу <Arrow /></a><a href="#capabilities" className="button secondary">Посмотреть возможности</a></div><p className="mvp-note"><span /> Сервис находится на стадии MVP и активно развивается</p></div><div className="hero-product"><div className="hero-grid-label">РАБОЧАЯ СРЕДА <b>01</b></div><EstimatePreview /></div></section>

    <section className="platform-statement" id="capabilities"><p className="overline">ЕДИНАЯ СРЕДА</p><div><h2>Один сервис — разные задачи<br />экспертной работы.</h2><p>Призма объединяет специализированные инструменты в единой профессиональной среде.</p></div></section>

    <section className="estimate-feature" id="estimate"><div className="section-heading"><div><p className="overline">01 / ЭКСПЕРТНАЯ СМЕТА</p><h2>Расчёт стоимости,<br />который можно проверить</h2></div><p>Инструмент для расчёта стоимости устранения недостатков с использованием рыночных цен, материалов и работ — с раскрытием исходных данных.</p></div><EstimatePreview compact /><div className="feature-list"><div><b>01</b><h3>Рыночные цены</h3><p>Ценовые предложения для обоснования стоимости.</p></div><div><b>02</b><h3>Материалы и работы</h3><p>Раздельный структурированный расчёт.</p></div><div><b>03</b><h3>Источники</h3><p>Данные, на которых основан расчёт.</p></div><div><b>04</b><h3>Методика</h3><p>Прозрачная структура экспертной работы.</p></div></div><a href="#more" className="text-link">Подробнее о смете <Arrow /></a></section>

    <section className="sources"><div className="source-copy"><p className="overline">ДАННЫЕ РАСЧЁТА</p><h2>Не просто<br />итоговая цифра</h2><p>Сохраняйте структуру расчёта и данные, на которых он основан.</p><a href="#sources" className="text-link">Посмотреть источники <Arrow /></a></div><div className="sources-ui"><div className="source-head"><span>Рыночные предложения</span><b>3 источника</b></div>{["МДФ фасад, эмаль / белый", "Столешница HPL, 38 мм", "Монтаж мебели, нормо-час"].map((s,i)=><div className="source-row" key={s}><b>{String(i+1).padStart(2,"0")}</b><div><strong>{s}</strong><span>{i===2 ? "Исполнитель работ" : "Товарное предложение"} · {i===0 ? "12.06.2026" : i===1 ? "10.06.2026" : "14.06.2026"}</span></div><em>{i===0?"18 400 ₽":i===1?"56 800 ₽":"3 950 ₽"}</em><i>Проверено</i></div>)}<div className="source-total">Расчётная стоимость <strong>248 600 ₽</strong></div></div></section>

    <section className="result-section"><div><p className="overline">РЕЗУЛЬТАТ РАСЧЁТА</p><h2>Стоимость устранения<br />недостатков</h2><strong className="big-price">438 420 ₽</strong><div className="price-breakdown"><p>Материалы <b>287 400 ₽</b></p><p>Работы <b>126 020 ₽</b></p><p>Прочие расходы <b>25 000 ₽</b></p></div></div><div className="report-sheet"><div className="report-logo"><PrismMark /> ПРИЗМА</div><p>ЭКСПЕРТНОЕ ИССЛЕДОВАНИЕ</p><h3>Расчёт стоимости устранения недостатков</h3><span>Объект: Кухонный гарнитур<br />Дата расчёта: 18.07.2026</span><div className="report-line"/><b>ИТОГОВАЯ СТОИМОСТЬ</b><strong>438 420 ₽</strong><small>Сформировано в PrismCore</small></div></section>

    <section className="indices" id="indices"><div className="indices-top"><div><p className="overline">02 / ПРИЗМА — ЭТО БОЛЬШЕ, ЧЕМ СМЕТА</p><h2>Индексы цен</h2></div><p>Второй доступный модуль PrismCore: анализ изменения стоимости и пересчёт цен между периодами на основе официальных статистических данных.</p></div><IndexChart /><div className="index-source-flow"><div><span className="eyeline">ОФИЦИАЛЬНЫЕ ДАННЫЕ</span><b>Официальные данные вместо ручных таблиц</b></div><div className="pipeline-flow"><span>Росстат</span><i>→</i><span>Структурированные данные</span><i>→</i><span className="flow-brand"><PrismMark /> PrismCore</span><i>→</i><span>Расчёт</span></div></div><a className="text-link" href="#index-more">Перейти к индексам <Arrow /></a></section>

    <section className="workflow"><p className="overline">ПРОЦЕСС РАБОТЫ</p><h2>От исходных данных до результата</h2><div className="workflow-grid">{[["01","Исходные данные","Параметры объекта и исходные сведения"],["02","Расчёт","Материалы, работы и ценовые предложения"],["03","Проверяемые источники","Зафиксированные основания расчёта"],["04","Профессиональный результат","Структурированные данные для работы эксперта"]].map(x=><div key={x[0]}><b>{x[0]}</b><span className="mini-ui"/><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></section>

    <section className="trust"><div><p className="overline">ПРИНЦИПЫ PRISMCORE</p><h2>Расчёт должен быть понятен<br />не только его автору</h2></div><div className="principles">{[["Структурированные данные","Исходные сведения не теряются внутри документа."],["Проверяемые источники","Понятно, откуда получены исходные значения."],["Прозрачная методика","Можно восстановить логику расчёта."],["Воспроизводимый результат","Расчёт можно проверить повторно."]].map((x,i)=><article key={x[0]}><b>0{i+1}</b><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section>

    <section className="ecosystem"><p className="overline">ПЛАТФОРМА PRISMCORE</p><h2>Платформа, которая развивается<br />вместе с экспертной практикой</h2><p className="ecosystem-copy">Призма объединяет специализированные инструменты в единой рабочей среде. Архитектура платформы открыта для новых профессиональных модулей.</p><div className="module-grid"><article className="module-card primary-module"><span className="status">ДОСТУПНО</span><b>01</b><h3>Экспертная смета</h3><p>Расчёт стоимости устранения недостатков.</p><ul><li>Расчёт стоимости</li><li>Материалы и работы</li><li>Рыночные цены</li><li>Источники</li></ul><a href="#estimate" className="text-link">О модуле <Arrow /></a></article><article className="module-card"><span className="status">MVP · ДОСТУПНО</span><b>02</b><h3>Индексы цен</h3><p>Работа с изменением стоимости между периодами.</p><ul><li>Динамика цен</li><li>Данные Росстата</li><li>CPI / PPI</li><li>Пересчёт стоимости</li></ul><a href="#indices" className="text-link">О модуле <Arrow /></a></article><article className="module-card future-module"><span className="status">В РАЗРАБОТКЕ</span><b>03</b><h3>Новые инструменты</h3><p>Платформа готова к развитию вместе с экспертной практикой.</p><div className="future-lines"><i /><i /><i /></div></article></div></section>

    <section className="positioning"><p>Эксперт принимает решение.<br /><span>Призма помогает работать с данными и расчётами.</span></p></section>
    <section className="final-cta" id="start"><p className="overline">PRISMCORE</p><h2>Профессиональные инструменты<br />в одной рабочей среде</h2><p>Используйте Призму для расчётов и работы с данными в экспертной практике.</p><div><a className="button primary" href="#login">Начать работу <Arrow /></a><a className="button secondary" href="#login">Войти</a></div></section>
    <footer><a className="logo" href="#top"><PrismMark /> <span>ПРИЗМА</span></a><div><b>Продукт</b><a>Возможности</a><a>Экспертная смета</a><a>Индексы</a><a>Тарифы</a></div><div><b>Материалы</b><a>База знаний</a><a>Поддержка</a></div><div><b>Правовая информация</b><a>Политика конфиденциальности</a><a>Пользовательское соглашение</a></div><small>© 2026 PrismCore. Профессиональная платформа для работы эксперта.</small></footer>
  </main>;
}
